<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateUserSecrets>true</GenerateUserSecrets>
    <RootNamespace>Internship_Task</RootNamespace>
    <UserSecretsId>c43b3aa0-a294-49f1-8cdd-e9916ab57a56</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.15.0" />
  </ItemGroup>

</Project>
